---
# Handlers for the pi_log role

- name: Restart pi-log service
  ansible.builtin.systemd:
    name: pi-log.service
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
